### ISSUE TITLE
Ubuntu 16.04 url wrong in Vagrant-File

### ISSUE THREAD

**Issue by StefanKuppelwieser** [siemens/codeface#56]
In the Vagrant-File is the Ubuntu-Version wrong

>  config.vm.box = "ffuenf/ubuntu-16.04-server-amd64"

does not exist

but you can solve this with 

>  config.vm.box = "ffuenf/ubuntu-16.04.1-server-amd64"

**Comment by wolfgangmauerer** [comment]
Am 07/12/2016 um 12:05 schrieb StefanKuppelwieser:
> In the Vagrant-File is the Ubuntu-Version wrong
> 
>     config.vm.box = "ffuenf/ubuntu-16.04-server-amd64"
> 
> does not exist
> 
> but you can solve this with
> 
>     config.vm.box = "ffuenf/ubuntu-16.04.1-server-amd64"

thanks for the information -- it seems that the source
does not make the old images available once an update is
made. Can you please send a patch that does the change?
See http://siemens.github.io/codeface/#/code. Thanks.

**Comment by wolfgangmauerer** [comment]
Changed in 46761d6408d6b137d1. Closing the issue.
